version: '3.9'
services:
  ms-transaction:
    container_name: 'ms-transtaction'
    build: ./ms-transaction/
    ports:
      - 3003:3003
    volumes:
      - ./ms-transaction/:/app/ms-transaction
    environment:
      - PORT=3003
      - DB_HOST=mongodb
      - DB_PORT=27017
      - DB_DATABASE=FraudShield-transactions
    depends_on:
      - mongodb
  mongodb:
    image: mongo:5
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - mongo-fraudshield-volume:/data/db
volumes:
  mongo-fraudshield-volume: