version: '3.9'
services:
  ms-transaction:
    container_name: 'ms-transtaction'
    build: ./ms-transaction/
    ports:
      - 3003:3003
    volumes:
      - ./ms-transaction/:/app/ms-transaction
    environment:
      - PORT=3003
    depends_on:
      - mongodb
  ms-customer:
    container_name: ms-customer
    build: ./ms-customer
    ports:
      - 3002:3002
    volumes:
      - ./ms-customer/:/app/ms-customer
    depends_on:
      - mongodb-customer
  mongodb:
    image: mongo:5
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - mongo-fraudshield-volume:/data/db

  mongodb-customer:
    image: mongo:5
    ports:
      - 27019:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - mongo-customer-volume:/data/db
volumes:
  mongo-fraudshield-volume:
  mongo-customer-volume: