version: '3.9'
services:
  ms-transaction:
    container_name: 'ms-transaction'
    build: ./ms-transaction/
    ports:
      - 3003:3003
    volumes:
      - ./ms-transaction/:/app/ms-transaction
    environment:
      - PORT=3003
      - DB_HOST=mongodb-transaction
      - DB_PORT=27017
      - DB_DATABASE=FraudShield-transactions
    depends_on:
      - mongodb-transaction

  ms-customer:
    container_name: 'ms-customer'
    build: ./ms-customer
    ports:
      - 3002:3002
    volumes:
      - ./ms-customer/:/app/ms-customer
    environment:
      - PORT=3002
      - DB_HOST=mongodb-customer
      - DB_PORT=27017
      - DB_DATABASE=fraudshield-customers
    depends_on:
      - mongodb-customer

  ms-anti-fraud:
    container_name: 'ms-anti-fraud'
    build: ./ms-anti-fraud/
    ports:
      - 3001:3001
    volumes:
      - ./ms-anti-fraud/:/app/ms-anti-fraud
    environment:
      - PORT=3001
      - DB_HOST=mongodb-anti-fraud
      - DB_PORT=27017
      - DB_DATABASE=fraudshield-anti-fraud
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
    depends_on:
      - mongodb-anti-fraud

  api-gateway:
    container_name: 'api-gateway'
    build: ./api-gateway
    ports:
      - 3000:3000
    volumes:
      - ./api-gateway/:/app/api-gateway
    environment:
      - API_GATEWAY_PORT=3000
      - ANTI_FRAUD_HOST=ms-anti-fraud
      - ANTI_FRAUD_PORT=3001
      - CUSTOMER_HOST=ms-customer
      - CUSTOMER_PORT=3002
      - TRANSACTION_HOST=ms-transaction
      - TRANSACTION_PORT=3003

  mongodb-anti-fraud:
    image: mongo:5
    ports:
      - 27018:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - mongo-anti-fraud-volume:/data/db

  mongodb-transaction:
    image: mongo:5
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - mongo-fraudshield-volume:/data/db

  mongodb-customer:
    image: mongo:5
    ports:
      - 27019:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - mongo-customer-volume:/data/db
      
volumes:
  mongo-fraudshield-volume:
  mongo-customer-volume:
  mongo-anti-fraud-volume:
